export enum PETS {
  panda = "panda",
  lion = "lion",
  lemur = "lemur",
  gorilla = "gorilla",
  eagles = "eagles",
  koala = "koala",
  tiger = "tiger",
  elephant = "elephant",
  otter = "otter",
  wolf = "wolf",
  alligator = "alligator",
  fox = "fox",
  bear = "bear",
  dolphin = "dolphin",
  leopard = "leopard",
  jaguar = "jaguar",
  rhinoceros = "rhinoceros",
  crocodile = "crocodile",
  macaw = "macaw",
  dragon = "dragon",
  sloth = "sloth",
  cheetah = "cheetah",
}
